## Pandas en 10 minutes

In [58]:
 #Pour intégrer les graphes à votre notebook, il suffit de faire
%matplotlib inline

from jyquickhelper import add_notebook_menu
add_notebook_menu()

On importe générallement les librairies suivantes

In [59]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Création d'objets

On créé une 'Series' en lui passant une liste de valeurs, en laissant pandas créer un index d'entiers

In [60]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

On créé un DataFrame en passant un array numpy, avec un index sur sur une date et des colonnes labellisées

In [61]:
dates = pd.date_range('20130101', periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


A         B         C         D
2013-01-01 -1.184356 -0.723850  0.391051  0.749447
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
2013-01-04  1.247574  0.102763 -0.254731 -1.270130
2013-01-05  0.605311  1.339097  0.313692  1.190966
2013-01-06 -0.582905  0.818028 -0.259498  0.305170

On peut également créer un DataFrame en passant un dictionnaire d'objets qui peut être converti en sorte de série.

In [62]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })

df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Chaque colonne a son propre dtypes

In [63]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

On peut afficher les premières lignes et les dernières

In [64]:
print(df.head())
print(df.tail())

                   A         B         C         D
2013-01-01 -1.184356 -0.723850  0.391051  0.749447
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
2013-01-04  1.247574  0.102763 -0.254731 -1.270130
2013-01-05  0.605311  1.339097  0.313692  1.190966
                   A         B         C         D
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
2013-01-04  1.247574  0.102763 -0.254731 -1.270130
2013-01-05  0.605311  1.339097  0.313692  1.190966
2013-01-06 -0.582905  0.818028 -0.259498  0.305170


On peut afficher l'index, les colonnes et les données numpy

In [65]:
print(df.index)
print(df.columns)
print(df.values)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[-1.18435607 -0.72384974  0.39105091  0.74944703]
 [ 0.02750198  0.24202818  0.93718807  0.35894525]
 [ 0.12108336  1.63369769 -0.13407011 -0.04799366]
 [ 1.24757372  0.10276272 -0.25473099 -1.27013015]
 [ 0.60531084  1.33909665  0.3136916   1.19096551]
 [-0.58290532  0.81802772 -0.25949756  0.30516996]]


La méthode describe permet d'afficher un résumé des données

In [66]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.039035  0.568627  0.165605  0.214401
std    0.856924  0.869988  0.472291  0.841637
min   -1.184356 -0.723850 -0.259498 -1.270130
25%   -0.430303  0.137579 -0.224566  0.040297
50%    0.074293  0.530028  0.089811  0.332058
75%    0.484254  1.208829  0.371711  0.651822
max    1.247574  1.633698  0.937188  1.190966

On peut faire la transposée, trier en fonction d'un axe ou des valeurs

In [67]:
print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.184356    0.027502    0.121083    1.247574    0.605311   -0.582905
B   -0.723850    0.242028    1.633698    0.102763    1.339097    0.818028
C    0.391051    0.937188   -0.134070   -0.254731    0.313692   -0.259498
D    0.749447    0.358945   -0.047994   -1.270130    1.190966    0.305170


In [68]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  0.749447  0.391051 -0.723850 -1.184356
2013-01-02  0.358945  0.937188  0.242028  0.027502
2013-01-03 -0.047994 -0.134070  1.633698  0.121083
2013-01-04 -1.270130 -0.254731  0.102763  1.247574
2013-01-05  1.190966  0.313692  1.339097  0.605311
2013-01-06  0.305170 -0.259498  0.818028 -0.582905

In [69]:
df.sort_values(by='B')

A         B         C         D
2013-01-01 -1.184356 -0.723850  0.391051  0.749447
2013-01-04  1.247574  0.102763 -0.254731 -1.270130
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-06 -0.582905  0.818028 -0.259498  0.305170
2013-01-05  0.605311  1.339097  0.313692  1.190966
2013-01-03  0.121083  1.633698 -0.134070 -0.047994

### Selection des données

#### Getting

Selection d'une colonne (équivalent à df.A)

In [70]:
print(df['A'])
print(df[0:3])
print(df['20130102':'20130104'])

2013-01-01   -1.184356
2013-01-02    0.027502
2013-01-03    0.121083
2013-01-04    1.247574
2013-01-05    0.605311
2013-01-06   -0.582905
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2013-01-01 -1.184356 -0.723850  0.391051  0.749447
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
                   A         B         C         D
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
2013-01-04  1.247574  0.102763 -0.254731 -1.270130


#### Selection par Label

En utilisant un label

In [71]:
df.loc[dates[0]]

A   -1.184356
B   -0.723850
C    0.391051
D    0.749447
Name: 2013-01-01 00:00:00, dtype: float64

Selection de plusieurs axes par label

In [72]:
df.loc[:,['A','B']]

A         B
2013-01-01 -1.184356 -0.723850
2013-01-02  0.027502  0.242028
2013-01-03  0.121083  1.633698
2013-01-04  1.247574  0.102763
2013-01-05  0.605311  1.339097
2013-01-06 -0.582905  0.818028

Avec le label slicing, les deux points de terminaisons sont INCLUS

In [73]:
df.loc['20130102':'20130104', ['A','B']]

A         B
2013-01-02  0.027502  0.242028
2013-01-03  0.121083  1.633698
2013-01-04  1.247574  0.102763

Obtenir une valeur scalaire

In [74]:
df.loc[dates[0],'A']

-1.184356071097634

Acces plus rapide (méthode équivalente à la précédente)

In [75]:
df.at[dates[0],'A']

-1.184356071097634

#### Selection par position

Integer : 

In [76]:
df.iloc[3]

A    1.247574
B    0.102763
C   -0.254731
D   -1.270130
Name: 2013-01-04 00:00:00, dtype: float64

Tranches d'entiers, similaire à numpy

In [77]:
df.iloc[3:5,0:2]

A         B
2013-01-04  1.247574  0.102763
2013-01-05  0.605311  1.339097

Par liste d'entiers

In [78]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02  0.027502  0.937188
2013-01-03  0.121083 -0.134070
2013-01-05  0.605311  0.313692

Découpage de ligne explicite

In [79]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994

Obtenir une valeur explicitement

In [80]:
df.iloc[1,1]

0.24202817975998675

Acces rapide au scalaire

In [81]:
df.iat[1,1]

0.24202817975998675

#### Indexation booléenne

En utilisant une valeur sur une colonne : 

In [82]:
df[df.A > 0]

A         B         C         D
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698 -0.134070 -0.047994
2013-01-04  1.247574  0.102763 -0.254731 -1.270130
2013-01-05  0.605311  1.339097  0.313692  1.190966

Opérateur where : 

In [83]:
df[df > 0]

A         B         C         D
2013-01-01       NaN       NaN  0.391051  0.749447
2013-01-02  0.027502  0.242028  0.937188  0.358945
2013-01-03  0.121083  1.633698       NaN       NaN
2013-01-04  1.247574  0.102763       NaN       NaN
2013-01-05  0.605311  1.339097  0.313692  1.190966
2013-01-06       NaN  0.818028       NaN  0.305170

Pour filter, on utilise la méthode isin()

In [84]:
df2 = df.copy()
df2['E'] = ['one', 'one','two','three','four','three']
print(df2)

df2[df2['E'].isin(['two','four'])]

                   A         B         C         D      E
2013-01-01 -1.184356 -0.723850  0.391051  0.749447    one
2013-01-02  0.027502  0.242028  0.937188  0.358945    one
2013-01-03  0.121083  1.633698 -0.134070 -0.047994    two
2013-01-04  1.247574  0.102763 -0.254731 -1.270130  three
2013-01-05  0.605311  1.339097  0.313692  1.190966   four
2013-01-06 -0.582905  0.818028 -0.259498  0.305170  three


A         B         C         D     E
2013-01-03  0.121083  1.633698 -0.134070 -0.047994   two
2013-01-05  0.605311  1.339097  0.313692  1.190966  four

#### Ajouter / modifier valeurs / colonnes

Ajouter une nouvelle colonne automatiquement aligne les données par index.

In [85]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))
print(s1)
df['F'] = s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64


Modifier une valeur par label

In [86]:
df.at[dates[0],'A'] = 0

In [87]:
df.loc[dates[0],'A']

0.0

Modifier une valeur par position

In [88]:
df.iat[0,1] = 0

Modifier une valeur en assignant un tableau numpy

In [89]:
df.loc[:,'D'] = np.array([5] * len(df))

In [90]:
df

A         B         C  D    F
2013-01-01  0.000000  0.000000  0.391051  5  NaN
2013-01-02  0.027502  0.242028  0.937188  5  1.0
2013-01-03  0.121083  1.633698 -0.134070  5  2.0
2013-01-04  1.247574  0.102763 -0.254731  5  3.0
2013-01-05  0.605311  1.339097  0.313692  5  4.0
2013-01-06 -0.582905  0.818028 -0.259498  5  5.0

#### Gérer les données manquantes

Pandas utilise le type np.nan pour représenter les valeurs manquantes. Ce n'est pas codé pour faire des calculs.

Reindex permet de changer/ajouter/supprimer les index d'un axe. Cette fonction retourne une copie des données

In [91]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1],'E'] = 1
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.391051  5  NaN  1.0
2013-01-02  0.027502  0.242028  0.937188  5  1.0  1.0
2013-01-03  0.121083  1.633698 -0.134070  5  2.0  NaN
2013-01-04  1.247574  0.102763 -0.254731  5  3.0  NaN

Pour supprimer les lignes contenant des NaN :

In [92]:
df1.dropna(how='any')

A         B         C  D    F    E
2013-01-02  0.027502  0.242028  0.937188  5  1.0  1.0

Remplacement des valeurs manquantes

In [93]:
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  0.000000  0.000000  0.391051  5  5.0  1.0
2013-01-02  0.027502  0.242028  0.937188  5  1.0  1.0
2013-01-03  0.121083  1.633698 -0.134070  5  2.0  5.0
2013-01-04  1.247574  0.102763 -0.254731  5  3.0  5.0

Obtenir le masque de booléen de l'emplacement des nan

In [94]:
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

### Opérations

#### Stats

Les opérations excluent généralement les données manquantes.

In [95]:
print(df.mean())
print(df.mean(1)) #Autre axe

A    0.236427
B    0.689269
C    0.165605
D    5.000000
F    3.000000
dtype: float64
2013-01-01    1.347763
2013-01-02    1.441344
2013-01-03    1.724142
2013-01-04    1.819121
2013-01-05    2.251620
2013-01-06    1.995125
Freq: D, dtype: float64


Situation avec des objets de dimmension différentes. En plus, pandas va automatiquement étendre la donnée sur la dimension spécifiée

In [96]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)

print(s)

df.sub(s, axis='index')

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64


A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -0.878917  0.633698 -1.134070  4.0  1.0
2013-01-04 -1.752426 -2.897237 -3.254731  2.0  0.0
2013-01-05 -4.394689 -3.660903 -4.686308  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [97]:
help(df.sub)

Help on method sub in module pandas.core.ops:

sub(other, axis='columns', level=None, fill_value=None) method of pandas.core.frame.DataFrame instance
    Get Subtraction of dataframe and other, element-wise (binary operator `sub`).
    
    Equivalent to ``dataframe - other``, but with support to substitute a fill_value
    for missing data in one of the inputs. With reverse version, `rsub`.
    
    Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
    arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
    
    Parameters
    ----------
    other : scalar, sequence, Series, or DataFrame
        Any single or multiple element data structure, or list-like object.
    axis : {0 or 'index', 1 or 'columns'}
        Whether to compare by the index (0 or 'index') or columns
        (1 or 'columns'). For Series input, axis to match Series index on.
    level : int or label
        Broadcast across a level, matching Index values on the
        passed MultiIndex leve

In [98]:
df.sub(s, axis='index')

A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -0.878917  0.633698 -1.134070  4.0  1.0
2013-01-04 -1.752426 -2.897237 -3.254731  2.0  0.0
2013-01-05 -4.394689 -3.660903 -4.686308  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

#### Apply

Appliquer des foncitons aux données

In [99]:
df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000  0.391051   5   NaN
2013-01-02  0.027502  0.242028  1.328239  10   1.0
2013-01-03  0.148585  1.875726  1.194169  15   3.0
2013-01-04  1.396159  1.978489  0.939438  20   6.0
2013-01-05  2.001470  3.317585  1.253129  25  10.0
2013-01-06  1.418565  4.135613  0.993632  30  15.0

In [100]:
df.apply((lambda x: x.max() - x.min()))

A    1.830479
B    1.633698
C    1.196686
D    0.000000
F    4.000000
dtype: float64

#### Histogramme

In [101]:
s = pd.Series(np.random.randint(0, 7, size=10))
print(s)
print(s.value_counts())

0    3
1    2
2    3
3    3
4    5
5    3
6    4
7    0
8    1
9    2
dtype: int64
3    4
2    2
0    1
1    1
4    1
5    1
dtype: int64


#### Methodes String

Les séries sont équipées de méthodes pour traiter les strings avec l'attribut str qui rend facile la manipulation de chaque élémen d'un tableau. On utilise régulièrement des expressions régulières.

In [102]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Regrouper

#### Concaténation

Pandas fournit des methodes pour facilement combiner des Series, DatFrame et des Panel objets avec des types variés de set logique pour les indexes et des fonctionnalités d'algèbre dans le cas de jointure / regroupement

On peut concaténer des objets pandas avec concat()

In [103]:
df = pd.DataFrame(np.random.randn(10, 4))
print(df)

          0         1         2         3
0  0.069013 -0.040383 -0.607478 -1.286906
1  1.270398 -0.523822  0.858627  0.751044
2  1.480067 -0.005535  0.244562 -0.224817
3 -0.730252  0.188720  0.105386 -0.600060
4 -0.844170  1.736848  0.190962  0.451052
5  0.181550  0.136675  0.892205  0.701368
6 -0.485632 -0.894081  0.532846 -1.228718
7  0.324976 -1.670890 -0.082170 -0.383374
8  0.589956 -0.859584  0.737789  1.193208
9  1.124989 -1.301511  2.010070  0.593592


In [104]:
pieces = [df[:3], df[3:7], df[7:]]

In [105]:
pd.concat(pieces)

0         1         2         3
0  0.069013 -0.040383 -0.607478 -1.286906
1  1.270398 -0.523822  0.858627  0.751044
2  1.480067 -0.005535  0.244562 -0.224817
3 -0.730252  0.188720  0.105386 -0.600060
4 -0.844170  1.736848  0.190962  0.451052
5  0.181550  0.136675  0.892205  0.701368
6 -0.485632 -0.894081  0.532846 -1.228718
7  0.324976 -1.670890 -0.082170 -0.383374
8  0.589956 -0.859584  0.737789  1.193208
9  1.124989 -1.301511  2.010070  0.593592

#### Jointures

On peut merger à la manière de requete SQL.

In [106]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

print(left)
print(right)

print(pd.merge(left, right, on='key'))

   key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     5
   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5


#### Append

In [107]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
df

A         B         C         D
0 -1.080456  0.981786  0.880026  1.144814
1 -1.665425 -0.577014  1.265051 -0.515127
2  0.342626 -0.635112  1.558737  1.070910
3 -0.236688 -1.178135  0.371970  0.268590
4 -0.478343  0.015331  0.835794  0.553637
5 -1.115995 -0.086228 -0.959499 -1.168225
6  0.615278 -0.550461 -0.328022  0.753208
7 -0.308374  1.024291 -1.437537  1.189244

In [108]:
s = df.iloc[3]
df.append(s, ignore_index=True)

A         B         C         D
0 -1.080456  0.981786  0.880026  1.144814
1 -1.665425 -0.577014  1.265051 -0.515127
2  0.342626 -0.635112  1.558737  1.070910
3 -0.236688 -1.178135  0.371970  0.268590
4 -0.478343  0.015331  0.835794  0.553637
5 -1.115995 -0.086228 -0.959499 -1.168225
6  0.615278 -0.550461 -0.328022  0.753208
7 -0.308374  1.024291 -1.437537  1.189244
8 -0.236688 -1.178135  0.371970  0.268590

#### Groupement

Le regroupement comprend les étapes suivantes :
   * Séparation de la donnée en groupes
   * Appliquer une fonction a chaque group indépendamment
   * Combiner les resultats dans une structure de données

In [109]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
'foo', 'bar', 'foo', 'foo'],
'B' : ['one', 'one', 'two', 'three',
'two', 'two', 'one', 'three'],
'C' : np.random.randn(8),
'D' : np.random.randn(8)})

In [110]:
df

A      B         C         D
0  foo    one  0.438443  0.479237
1  bar    one -0.457745 -0.363322
2  foo    two  0.684435 -0.421288
3  bar  three -0.620241  0.267481
4  foo    two -0.032591  2.801863
5  bar    two  0.878103 -0.064529
6  foo    one -0.000896 -1.695125
7  foo  three  1.341618 -0.165415

Groupement et somme des groupes

In [111]:
df.groupby('A').sum()

C         D
A                      
bar -0.199883 -0.160370
foo  2.431011  0.999271

Groupement de multiple colonnes

In [112]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.457745 -0.363322
    three -0.620241  0.267481
    two    0.878103 -0.064529
foo one    0.437547 -1.215888
    three  1.341618 -0.165415
    two    0.651845  2.380574

#### Reformation

Stack

In [113]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
'foo', 'foo', 'qux', 'qux'],
['one', 'two', 'one', 'two',
'one', 'two', 'one', 'two']]))

index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
df2 = df[:4]
df2

A         B
first second                    
bar   one    -0.347244 -0.780456
      two    -0.394013 -0.561465
baz   one     1.055322  2.620028
      two    -1.443417  0.514155

La méthode stack() compresses un level dans les colonnes du dataframe


In [114]:
stacked = df2.stack()
stacked

first  second   
bar    one     A   -0.347244
               B   -0.780456
       two     A   -0.394013
               B   -0.561465
baz    one     A    1.055322
               B    2.620028
       two     A   -1.443417
               B    0.514155
dtype: float64

Avec une 'stacked' dataframe ou série, l'opération inverse est unstack()