## Pandas en 10 minutes

In [1]:
 #Pour intégrer les graphes à votre notebook, il suffit de faire
%matplotlib inline

from jyquickhelper import add_notebook_menu
add_notebook_menu()

On importe générallement les librairies suivantes

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Création d'objets

On créé une 'Series' en lui passant une liste de valeurs, en laissant pandas créer un index d'entiers

In [3]:
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

On créé un DataFrame en passant un array numpy, avec un index sur sur une date et des colonnes labellisées

In [4]:
dates = pd.date_range('20130101', periods=6)
print(dates)

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')


A         B         C         D
2013-01-01  0.022840 -0.137788 -0.587941  1.494743
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-05  0.878803 -0.089553  1.424419 -0.997550
2013-01-06 -0.010371 -0.150360  0.533806 -1.542545

On peut également créer un DataFrame en passant un dictionnaire d'objets qui peut être converti en sorte de série.

In [5]:
df2 = pd.DataFrame({ 'A' : 1.,
'B' : pd.Timestamp('20130102'),
'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
'D' : np.array([3] * 4,dtype='int32'),
'E' : pd.Categorical(["test","train","test","train"]),
'F' : 'foo' })

df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Chaque colonne a son propre dtypes

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

On peut afficher les premières lignes et les dernières

In [7]:
print(df.head())
print(df.tail())

                   A         B         C         D
2013-01-01  0.022840 -0.137788 -0.587941  1.494743
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-05  0.878803 -0.089553  1.424419 -0.997550
                   A         B         C         D
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-05  0.878803 -0.089553  1.424419 -0.997550
2013-01-06 -0.010371 -0.150360  0.533806 -1.542545


On peut afficher l'index, les colonnes et les données numpy

In [8]:
print(df.index)
print(df.columns)
print(df.values)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0.02284049 -0.13778847 -0.58794082  1.49474291]
 [ 0.77082183  1.30180362  1.07219953 -1.14550279]
 [ 1.49175339 -1.27851082  1.17262115  1.46467732]
 [ 0.31044716  1.02190846  0.64544517  0.42576268]
 [ 0.87880268 -0.08955306  1.42441928 -0.99754974]
 [-0.01037135 -0.15035959  0.53380592 -1.54254497]]


La méthode describe permet d'afficher un résumé des données

In [9]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.577382  0.111250  0.710092 -0.050069
std    0.581132  0.932624  0.717700  1.358859
min   -0.010371 -1.278511 -0.587941 -1.542545
25%    0.094742 -0.147217  0.561716 -1.108515
50%    0.540634 -0.113671  0.858822 -0.285894
75%    0.851807  0.744043  1.147516  1.204949
max    1.491753  1.301804  1.424419  1.494743

On peut faire la transposée, trier en fonction d'un axe ou des valeurs

In [10]:
print(df.T)

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.022840    0.770822    1.491753    0.310447    0.878803   -0.010371
B   -0.137788    1.301804   -1.278511    1.021908   -0.089553   -0.150360
C   -0.587941    1.072200    1.172621    0.645445    1.424419    0.533806
D    1.494743   -1.145503    1.464677    0.425763   -0.997550   -1.542545


In [11]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2013-01-01  1.494743 -0.587941 -0.137788  0.022840
2013-01-02 -1.145503  1.072200  1.301804  0.770822
2013-01-03  1.464677  1.172621 -1.278511  1.491753
2013-01-04  0.425763  0.645445  1.021908  0.310447
2013-01-05 -0.997550  1.424419 -0.089553  0.878803
2013-01-06 -1.542545  0.533806 -0.150360 -0.010371

In [12]:
df.sort_values(by='B')

A         B         C         D
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-06 -0.010371 -0.150360  0.533806 -1.542545
2013-01-01  0.022840 -0.137788 -0.587941  1.494743
2013-01-05  0.878803 -0.089553  1.424419 -0.997550
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-02  0.770822  1.301804  1.072200 -1.145503

### Selection des données

#### Getting

Selection d'une colonne (équivalent à df.A)

In [13]:
print(df['A'])
print(df[0:3])
print(df['20130102':'20130104'])

2013-01-01    0.022840
2013-01-02    0.770822
2013-01-03    1.491753
2013-01-04    0.310447
2013-01-05    0.878803
2013-01-06   -0.010371
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2013-01-01  0.022840 -0.137788 -0.587941  1.494743
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
                   A         B         C         D
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763


#### Selection par Label

En utilisant un label

In [14]:
df.loc[dates[0]]

A    0.022840
B   -0.137788
C   -0.587941
D    1.494743
Name: 2013-01-01 00:00:00, dtype: float64

Selection de plusieurs axes par label

In [15]:
df.loc[:,['A','B']]

A         B
2013-01-01  0.022840 -0.137788
2013-01-02  0.770822  1.301804
2013-01-03  1.491753 -1.278511
2013-01-04  0.310447  1.021908
2013-01-05  0.878803 -0.089553
2013-01-06 -0.010371 -0.150360

Avec le label slicing, les deux points de terminaisons sont INCLUS

In [16]:
df.loc['20130102':'20130104', ['A','B']]

A         B
2013-01-02  0.770822  1.301804
2013-01-03  1.491753 -1.278511
2013-01-04  0.310447  1.021908

Obtenir une valeur scalaire

In [17]:
df.loc[dates[0],'A']

0.022840486206455575

Acces plus rapide (méthode équivalente à la précédente)

In [18]:
df.at[dates[0],'A']

0.022840486206455575

#### Selection par position

Integer : 

In [19]:
df.iloc[3]

A    0.310447
B    1.021908
C    0.645445
D    0.425763
Name: 2013-01-04 00:00:00, dtype: float64

Tranches d'entiers, similaire à numpy

In [20]:
df.iloc[3:5,0:2]

A         B
2013-01-04  0.310447  1.021908
2013-01-05  0.878803 -0.089553

Par liste d'entiers

In [21]:
df.iloc[[1,2,4],[0,2]]

A         C
2013-01-02  0.770822  1.072200
2013-01-03  1.491753  1.172621
2013-01-05  0.878803  1.424419

Découpage de ligne explicite

In [22]:
df.iloc[1:3,:]

A         B         C         D
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677

Obtenir une valeur explicitement

In [23]:
df.iloc[1,1]

1.30180361565005

Acces rapide au scalaire

In [24]:
df.iat[1,1]

1.30180361565005

#### Indexation booléenne

En utilisant une valeur sur une colonne : 

In [25]:
df[df.A > 0]

A         B         C         D
2013-01-01  0.022840 -0.137788 -0.587941  1.494743
2013-01-02  0.770822  1.301804  1.072200 -1.145503
2013-01-03  1.491753 -1.278511  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-05  0.878803 -0.089553  1.424419 -0.997550

Opérateur where : 

In [26]:
df[df > 0]

A         B         C         D
2013-01-01  0.022840       NaN       NaN  1.494743
2013-01-02  0.770822  1.301804  1.072200       NaN
2013-01-03  1.491753       NaN  1.172621  1.464677
2013-01-04  0.310447  1.021908  0.645445  0.425763
2013-01-05  0.878803       NaN  1.424419       NaN
2013-01-06       NaN       NaN  0.533806       NaN

Pour filter, on utilise la méthode isin()

In [27]:
df2 = df.copy()
df2['E'] = ['one', 'one','two','three','four','three']
print(df2)

df2[df2['E'].isin(['two','four'])]

                   A         B         C         D      E
2013-01-01  0.022840 -0.137788 -0.587941  1.494743    one
2013-01-02  0.770822  1.301804  1.072200 -1.145503    one
2013-01-03  1.491753 -1.278511  1.172621  1.464677    two
2013-01-04  0.310447  1.021908  0.645445  0.425763  three
2013-01-05  0.878803 -0.089553  1.424419 -0.997550   four
2013-01-06 -0.010371 -0.150360  0.533806 -1.542545  three


A         B         C         D     E
2013-01-03  1.491753 -1.278511  1.172621  1.464677   two
2013-01-05  0.878803 -0.089553  1.424419 -0.997550  four

#### Ajouter / modifier valeurs / colonnes

Ajouter une nouvelle colonne automatiquement aligne les données par index.

In [28]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102', periods=6))
print(s1)
df['F'] = s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64


Modifier une valeur par label

In [29]:
df.at[dates[0],'A'] = 0

In [30]:
df.loc[dates[0],'A']

0.0

Modifier une valeur par position

In [31]:
df.iat[0,1] = 0

Modifier une valeur en assignant un tableau numpy

In [32]:
df.loc[:,'D'] = np.array([5] * len(df))

In [33]:
df

A         B         C  D    F
2013-01-01  0.000000  0.000000 -0.587941  5  NaN
2013-01-02  0.770822  1.301804  1.072200  5  1.0
2013-01-03  1.491753 -1.278511  1.172621  5  2.0
2013-01-04  0.310447  1.021908  0.645445  5  3.0
2013-01-05  0.878803 -0.089553  1.424419  5  4.0
2013-01-06 -0.010371 -0.150360  0.533806  5  5.0

#### Gérer les données manquantes

Pandas utilise le type np.nan pour représenter les valeurs manquantes. Ce n'est pas codé pour faire des calculs.

Reindex permet de changer/ajouter/supprimer les index d'un axe. Cette fonction retourne une copie des données

In [34]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1],'E'] = 1
df1

A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.587941  5  NaN  1.0
2013-01-02  0.770822  1.301804  1.072200  5  1.0  1.0
2013-01-03  1.491753 -1.278511  1.172621  5  2.0  NaN
2013-01-04  0.310447  1.021908  0.645445  5  3.0  NaN

Pour supprimer les lignes contenant des NaN :

In [35]:
df1.dropna(how='any')

A         B       C  D    F    E
2013-01-02  0.770822  1.301804  1.0722  5  1.0  1.0

Remplacement des valeurs manquantes

In [36]:
df1.fillna(value=5)

A         B         C  D    F    E
2013-01-01  0.000000  0.000000 -0.587941  5  5.0  1.0
2013-01-02  0.770822  1.301804  1.072200  5  1.0  1.0
2013-01-03  1.491753 -1.278511  1.172621  5  2.0  5.0
2013-01-04  0.310447  1.021908  0.645445  5  3.0  5.0

Obtenir le masque de booléen de l'emplacement des nan

In [37]:
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

### Opérations

#### Stats

Les opérations excluent généralement les données manquantes.

In [38]:
print(df.mean())
print(df.mean(1)) #Autre axe

A    0.573576
B    0.134215
C    0.710092
D    5.000000
F    3.000000
dtype: float64
2013-01-01    1.103015
2013-01-02    1.828965
2013-01-03    1.677173
2013-01-04    1.995560
2013-01-05    2.242734
2013-01-06    2.074615
Freq: D, dtype: float64


Situation avec des objets de dimmension différentes. En plus, pandas va automatiquement étendre la donnée sur la dimension spécifiée

In [39]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)

print(s)

df.sub(s, axis='index')

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64


A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03  0.491753 -2.278511  0.172621  4.0  1.0
2013-01-04 -2.689553 -1.978092 -2.354555  2.0  0.0
2013-01-05 -4.121197 -5.089553 -3.575581  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

In [40]:
help(df.sub)

Help on method sub in module pandas.core.ops:

sub(other, axis='columns', level=None, fill_value=None) method of pandas.core.frame.DataFrame instance
    Get Subtraction of dataframe and other, element-wise (binary operator `sub`).
    
    Equivalent to ``dataframe - other``, but with support to substitute a fill_value
    for missing data in one of the inputs. With reverse version, `rsub`.
    
    Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
    arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
    
    Parameters
    ----------
    other : scalar, sequence, Series, or DataFrame
        Any single or multiple element data structure, or list-like object.
    axis : {0 or 'index', 1 or 'columns'}
        Whether to compare by the index (0 or 'index') or columns
        (1 or 'columns'). For Series input, axis to match Series index on.
    level : int or label
        Broadcast across a level, matching Index values on the
        passed MultiIndex leve

In [41]:
df.sub(s, axis='index')

A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03  0.491753 -2.278511  0.172621  4.0  1.0
2013-01-04 -2.689553 -1.978092 -2.354555  2.0  0.0
2013-01-05 -4.121197 -5.089553 -3.575581  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

#### Apply

Appliquer des foncitons aux données

In [42]:
df.apply(np.cumsum)

A         B         C   D     F
2013-01-01  0.000000  0.000000 -0.587941   5   NaN
2013-01-02  0.770822  1.301804  0.484259  10   1.0
2013-01-03  2.262575  0.023293  1.656880  15   3.0
2013-01-04  2.573022  1.045201  2.302325  20   6.0
2013-01-05  3.451825  0.955648  3.726744  25  10.0
2013-01-06  3.441454  0.805289  4.260550  30  15.0

In [43]:
df.apply((lambda x: x.max() - x.min()))

A    1.502125
B    2.580314
C    2.012360
D    0.000000
F    4.000000
dtype: float64

#### Histogramme

In [44]:
s = pd.Series(np.random.randint(0, 7, size=10))
print(s)
print(s.value_counts())

0    0
1    0
2    6
3    2
4    0
5    6
6    1
7    2
8    5
9    0
dtype: int64
0    4
2    2
6    2
1    1
5    1
dtype: int64


#### Methodes String

Les séries sont équipées de méthodes pour traiter les strings avec l'attribut str qui rend facile la manipulation de chaque élémen d'un tableau. On utilise régulièrement des expressions régulières.

In [45]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Regrouper

#### Concaténation

Pandas fournit des methodes pour facilement combiner des Series, DatFrame et des Panel objets avec des types variés de set logique pour les indexes et des fonctionnalités d'algèbre dans le cas de jointure / regroupement

On peut concaténer des objets pandas avec concat()

In [46]:
df = pd.DataFrame(np.random.randn(10, 4))
print(df)

          0         1         2         3
0  0.521402  1.796737  0.466931  1.216478
1 -0.290890 -0.093095 -1.333270  0.481634
2 -0.097377 -0.689179  1.102952  1.767773
3  0.849969 -0.120573  0.170778  1.306829
4 -1.575077 -0.066620 -0.511321  0.174610
5 -0.974735 -0.237773  0.609539 -1.196054
6  0.487931  0.354117  0.481754 -1.613418
7  0.499504  0.301069 -1.133783  0.097880
8  0.590346  0.463753  0.100697  0.806764
9 -1.865869 -0.674052  0.599669  0.418912


In [47]:
pieces = [df[:3], df[3:7], df[7:]]

In [48]:
pd.concat(pieces)

0         1         2         3
0  0.521402  1.796737  0.466931  1.216478
1 -0.290890 -0.093095 -1.333270  0.481634
2 -0.097377 -0.689179  1.102952  1.767773
3  0.849969 -0.120573  0.170778  1.306829
4 -1.575077 -0.066620 -0.511321  0.174610
5 -0.974735 -0.237773  0.609539 -1.196054
6  0.487931  0.354117  0.481754 -1.613418
7  0.499504  0.301069 -1.133783  0.097880
8  0.590346  0.463753  0.100697  0.806764
9 -1.865869 -0.674052  0.599669  0.418912

#### Jointures

On peut merger à la manière de requete SQL.

In [49]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

print(left)
print(right)

print(pd.merge(left, right, on='key'))

   key  lval
0  foo     1
1  foo     2
   key  rval
0  foo     4
1  foo     5
   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5


#### Append

In [50]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
df

A         B         C         D
0 -0.910548  0.703509  0.109553 -0.184034
1  0.610474 -1.586906  1.094916 -0.757138
2  0.410086  0.672223 -1.794147  0.577572
3 -0.696705  0.749335  0.183991 -0.977423
4 -0.241543 -0.262477 -1.796894  1.168579
5 -0.458845  0.008596  0.511633  1.491573
6  0.413318 -1.234969  0.204331 -0.904676
7  0.074012  0.009319 -1.835974  0.524385

In [51]:
s = df.iloc[3]
df.append(s, ignore_index=True)

A         B         C         D
0 -0.910548  0.703509  0.109553 -0.184034
1  0.610474 -1.586906  1.094916 -0.757138
2  0.410086  0.672223 -1.794147  0.577572
3 -0.696705  0.749335  0.183991 -0.977423
4 -0.241543 -0.262477 -1.796894  1.168579
5 -0.458845  0.008596  0.511633  1.491573
6  0.413318 -1.234969  0.204331 -0.904676
7  0.074012  0.009319 -1.835974  0.524385
8 -0.696705  0.749335  0.183991 -0.977423

#### Groupement

Le regroupement comprend les étapes suivantes :
   * Séparation de la donnée en groupes
   * Appliquer une fonction a chaque group indépendamment
   * Combiner les resultats dans une structure de données

In [52]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
'foo', 'bar', 'foo', 'foo'],
'B' : ['one', 'one', 'two', 'three',
'two', 'two', 'one', 'three'],
'C' : np.random.randn(8),
'D' : np.random.randn(8)})

In [53]:
df

A      B         C         D
0  foo    one -0.471184  0.762091
1  bar    one  2.406332 -2.022383
2  foo    two -0.644519 -1.108203
3  bar  three  1.045285 -0.258954
4  foo    two -0.877631 -0.063593
5  bar    two -0.299086  0.473943
6  foo    one  1.030272 -0.925755
7  foo  three -1.580951  1.336636

Groupement et somme des groupes

In [54]:
df.groupby('A').sum()

C         D
A                      
bar  3.152531 -1.807394
foo -2.544012  0.001176

Groupement de multiple colonnes

In [55]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one    2.406332 -2.022383
    three  1.045285 -0.258954
    two   -0.299086  0.473943
foo one    0.559089 -0.163664
    three -1.580951  1.336636
    two   -1.522150 -1.171796

#### Reformation

Stack

In [56]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
'foo', 'foo', 'qux', 'qux'],
['one', 'two', 'one', 'two',
'one', 'two', 'one', 'two']]))

index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
df2 = df[:4]
df2

A         B
first second                    
bar   one    -0.794092  0.524847
      two     0.341934 -1.595808
baz   one    -0.262787 -1.713956
      two     0.732998 -0.040637

La méthode stack() compresses un level dans les colonnes du dataframe


In [57]:
stacked = df2.stack()
stacked

first  second   
bar    one     A   -0.794092
               B    0.524847
       two     A    0.341934
               B   -1.595808
baz    one     A   -0.262787
               B   -1.713956
       two     A    0.732998
               B   -0.040637
dtype: float64

Avec une 'stacked' dataframe ou série, l'opération inverse est unstack()